# docker/core/monitoring/logging/visualization/conf/kibana.yml

server:
  name: kibana
  host: "0.0.0.0"
  port: 5601

elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}

monitoring:
  ui:
    container:
      elasticsearch:
        enabled: true

xpack:
  security:
    enabled: true
    encryptionKey: ${ENCRYPTION_KEY}
    session:
      idleTimeout: 1h
      lifespan: 24h
