# docker/core/monitoring/logging/store/conf/elasticsearch.yaml

cluster:
  name: hotflicks-logging

node:
  name: ${HOSTNAME}

path:
  data: /usr/share/elasticsearch/data
  logs: /usr/share/elasticsearch/logs

network:
  host: 0.0.0.0

xpack:
  security:
    enabled: true
    transport:
      ssl:
        enabled: true

discovery:
  seed_hosts: []

bootstrap:
  memory_lock: true
