# docker/core/edge-router/conf/traefik.yaml
global:
  sendAnonymousUsage: false
  checkNewVersion: false

log:
  level: INFO
  format: json

accessLog:
  format: json
  fields:
    defaultMode: keep
    headers:
      defaultMode: drop

api:
  dashboard: true
  insecure: false

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls: {}
  metrics:
    address: ":8082"

providers:
  consul:
    endpoints:
      - "service-registry:8500"
    token: "{{ .Env.CONSUL_TOKEN }}"
    rootKey: "traefik"
    namespaces: ["default", "streaming"]
    refreshInterval: "30s"

  file:
    directory: "/etc/traefik/dynamic"
    watch: true

certificatesResolvers:
  default:
    acme:
      email: "admin@hotflicks.local"
      storage: "/etc/traefik/acme/acme.json"
      tlsChallenge: {}

pilot:
  enabled: false
