# docker/core/monitoring/alerting/conf/alertmanager.yml

global:
  resolve_timeout: 5m
  smtp_smarthost: "smtp.hotflicks.local:587"
  smtp_from: "alertmanager@hotflicks.local"
  smtp_auth_username: "${SMTP_USER}"
  smtp_auth_password: "${SMTP_PASSWORD}"

route:
  group_by: ["alertname", "cluster", "service"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: "team-ops"

receivers:
  - name: "team-ops"
    email_configs:
      - to: "ops@hotflicks.local"
        send_resolved: true
    slack_configs:
      - api_url: "${SLACK_WEBHOOK_URL}"
        channel: "#alerts"
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "cluster", "service"]
